version: 2.1
orbs:
  node:   circleci/node@4.7.0
  aws-s3: circleci/aws-s3@3.0

jobs:
  build_and_test:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/project/build
          paths:
            - .
  deploy:
    docker:
      - image: cimg/python:3.6
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            NAME_HASH="$(echo ${CIRCLE_BRANCH} | md5sum | cut -c -7)"
            BUCKET_LOC="${NAME_HASH}-${CIRCLE_BRANCH##*/}"
            [[ CIRCLE_BRANCH != "main" ]] || BUCKET_LOC="${CIRCLE_SHA1}"
            echo "export BUCKET_LOC=${BUCKET_LOC}" >> $BASH_ENV
            source $BASH_ENV
          name: Modify branch name
      - aws-s3/sync:
          arguments: |
            --delete
          from: .
          to: "s3://blige-app/${BUCKET_LOC}"
  target:
    docker:
      - image: cimg/python:3.6
    steps:
      - run:
          name: Create Target File
          command: |
            echo "${CIRCLE_SHA1}" >> target
      - aws-s3/sync:
          arguments: |
            --content-type="text/plain"
          from: .
          to: "s3://blige-app/"

workflows:
  on_commit:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
      - target:
          requires:
            - deploy
          filters:
            branches:
              only: main

